"""add mcp_server_configs table and user is_admin

Revision ID: 0e07298280dd
Revises: 07b49ca40821
Create Date: 2026-03-28 23:13:03.591148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e07298280dd'
down_revision: Union[str, None] = '07b49ca40821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_server_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.Enum('STDIO', 'HTTP', 'SSE', name='mcptransport'), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('env', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('USER', 'GLOBAL', name='mcpconfigkind'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcp_config_user_id', 'mcp_server_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_mcp_server_configs_name'), 'mcp_server_configs', ['name'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_mcp_server_configs_name'), table_name='mcp_server_configs')
    op.drop_index('ix_mcp_config_user_id', table_name='mcp_server_configs')
    op.drop_table('mcp_server_configs')
    # ### end Alembic commands ###
